# Read the Docs configuration file for Sphinx projects
# https://docs.readthedocs.io/en/stable/config-file/v2.html

# Required
version: 2

# OS, Python version and any other tools
build:
  os: ubuntu-22.04
  tools:
    python: '3.7'


# Sphinx configuration
sphinx:
  configuration: doc/conf.py

# Python requirements for building documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: doc/requirements_rtd.txt
    - method: setuptools
      path: .
